# Generated by Django 5.2.4 on 2025-07-24 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(db_column='IDUsuario', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('senha', models.CharField(db_column='Senha', max_length=255)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, db_column='DTInclusao')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.AutoField(db_column='IDOperacao', primary_key=True, serialize=False)),
                ('parametros', models.CharField(db_column='Parametros', max_length=255)),
                ('resultado', models.CharField(db_column='Resultado', max_length=255)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, db_column='DTInclusao')),
                ('usuario', models.ForeignKey(db_column='IDUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
